import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'app_name': 'PregnancyUAE',
          'search_hint': 'Search services, experts...',
          'week_title': 'Week 28',
          'days_left': '84 days left',
          'due_date': 'Due Date: Oct 12, 2026',
          'weekly_focus': 'Your baby is now the size of an eggplant!',
          'categories': 'Categories',
          'see_all': 'See all',
          'meet_experts': 'Meet Our Experts',
          'recommended_for_you': 'Recommended for You',
          'all': 'All',
          'medical': 'Medical',
          'wellness': 'Wellness',
          'shopping': 'Shopping',
          'book_now': 'Book Now',
          'specialist': 'Specialist',
          'rating': 'Rating',
          'location': 'Location',
          'favorites': 'Favorites',
          'notifications': 'Notifications',
          'home': 'Home',
          'appointments': 'Appointments',
          'services': 'Services',
          'community': 'Community',
          'profile': 'Profile',
          'massage': 'Massage',
          'foot_spa': 'Foot Spa',
          'nutritionist': 'Nutritionist',
          'fitness': 'Fitness',
          'lactation': 'Lactation',
          'therapy': 'Therapy',
          'home_care': 'Home Care',
          'baby_care': 'Baby Care',
          'top_rated': 'Top Rated',
          'prenatal': 'Prenatal',
          'postpartum': 'Postpartum',
          'home_visit': 'Home visit',
          'at_provider': 'At Provider',
          'reviews': 'reviews',
          'prenatal_care': 'Prenatal Care',
          'baby_tracking': 'Baby Tracking',
          'ultrasound': 'Ultrasound',
          'calming_prenatal_massage': 'Calming Prenatal Massage',
          'massage_description': 'Experience gentle care designed to reduce stress, ease body aches, & support your pregnancy journey.',
          'starting_price': 'Starting \$40',
          'duration': '60 min ~',
          'bookings': 'Bookings',
          'chat': 'Chat',
        },
      };
}
